name: "Skilled Teleportation"
description: "Generate an archive of GitHub Actions to move to GitHub Enterprise Server."
author: "Natalie Somersall (@some-natalie)"
branding:
  color: green
  icon: book-open

inputs:
  sync_skills:
    description: "Whether to sync skills from the github.com/skills organization.  Set this to 'false' to skip Skills."
    default: "true"
    required: false
  sync_setup:
    description: "Whether to sync the setup-LANGUAGE actions from the github.com/actions organization.  Set this to 'false' to skip."
    default: "true"
    required: false
  sync_templates:
    description: "Whether to sync the get started templates from the github.com/actions organization.  Set this to 'false' to skip."
    default: "true"
    required: false
  list_file:
    description: "The list of additional skills to export."
    required: false

runs:
  using: "composite"
  steps:
    - name: "Checkout the repo"
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        token: ${{ github.token }}

    - name: "Setup actions-sync"
      shell: bash
      run: |
        # get the latest release
        curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ github.token }}" \
            https://api.github.com/repos/actions/actions-sync/releases/latest | \
        jq -r '.assets[].browser_download_url' | \
        grep "linux_amd64" | \
        xargs wget

        # untar the release
        tar -xzf *_linux_amd64.tar.gz

    - name: "Setup the cache directory"
      shell: bash
      run: |
        # Make a temp directory in the relative working directory
        mkdir -p tmp/cache

    - name: "Pull the GitHub Skills repositories"
      if: ${{ inputs.sync_skills }} = "true"
      shell: bash
      run: |
        # Sync all of github.com/skills
        curl -s https://api.github.com/orgs/skills/repos | jq -r '.[].full_name' | while read -r line ; do
            bin/actions-sync pull --cache-dir tmp/cache --repo-name "$line"
        done

        # Get the list of dependencies for the Skills organization
        curl https://raw.githubusercontent.com/some-natalie/skilled-teleportation/v2/skills-dependencies.txt -o skills-dependencies.txt -s

        # Sync dependencies for the Skills organization
        grep -v '^#' skills-dependencies.txt | grep . | while read -r line ; do
            bin/actions-sync pull --cache-dir tmp/cache --repo-name "$line"
        done

    - name: "Pull the setup-language repositories"
      if: ${{ inputs.sync_setup }} = "true"
      shell: bash
      run: |
        # Sync all of github.com/actions/setup-*
        curl -s https://api.github.com/orgs/actions/repos | jq -r '.[].name' | while read -r line ; do
            if [[ "$line" == "setup-*" ]]; then
                bin/actions-sync pull --cache-dir tmp/cache --repo-name "$line"
            fi
        done

    - name: "Pull the template Actions repositories"
      if: ${{ inputs.sync_templates }} = "true"
      shell: bash
      run: |
        # Get the list of template repositories
        curl https://raw.githubusercontent.com/some-natalie/skilled-teleportation/v2/template-actions.txt -o template-actions.txt -s

        # Sync all of github.com/actions templates
        grep -v '^#' template-actions.txt | grep . | while read -r line ; do
            bin/actions-sync pull --cache-dir tmp/cache --repo-name "$line"
        done

    - name: "Pull any additional Actions repositories"
      if: ${{ inputs.list_file }}
      shell: bash
      run: |
        # Sync any additional Actions repositories
        grep -v '^#' ${{ inputs.list_file }} | grep . | while read -r line ; do
            bin/actions-sync pull --cache-dir tmp/cache --repo-name "$line"
        done

    - name: "Copy the actions-sync utility into the cache dir"
      shell: bash
      run: |
        cp bin/actions-sync tmp/
        chmod +x tmp/actions-sync

    - name: "Copy in the push script"
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/some-natalie/skilled-teleportation/v2/scripts/teleport-push.sh -o teleport-push.sh -s
        cp teleport-push.sh tmp/
        chmod +x tmp/teleport-push.sh

    - name: "Upload the zip archive"
      uses: actions/upload-artifact@v4
      with:
        name: "teleport-archive"
        path: |
          tmp/*
        if-no-files-found: error
